<?php

namespace Orwallet\FoxtrotSdk;

class ErrorCodes
{
    public static $codes = [
        "B0001" => "System is busy",
        "A0001" => "Parameter [merNo] can not be empty",
        "A0002" => "The parameter [merNo] format error",
        "A0003" => "Parameter [amount] can not be empty",
        "A0004" => "The parameter [amount] format error",
        "A0005" => "Parameter [productInfo] can not be empty",
        "A0006" => "Parameter [productInfo] length exceeds limit",
        "A0007" => "Parameter [currency] can not be empty",
        "A0008" => "The parameter [currency] format error",
        "A0009" => "Parameter [cardNum] can not be empty",
        "A0010" => "The parameter [cardNum] format error",
        "A0011" => "Parameter [year] can not be empty",
        "A0012" => "The parameter [year] format error",
        "A0013" => "Parameter [month] can not be empty",
        "A0014" => "The parameter [month] format error",
        "A0015" => "The period of validity cannot be less than the current time",
        "A0016" => "Parameter [cvv2] can not be empty",
        "A0017" => "The parameter [cvv2] format error",
        "A0018" => "Parameter [firstName] can not be empty",
        "A0019" => "The parameter [firstName] format error",
        "A0020" => "Parameter [lastName] can not be empty",
        "A0021" => "The parameter [lastName] format error",
        "A0022" => "Parameter [address] can not be empty",
        "A0023" => "Parameter [city] can not be empty",
        "A0024" => "Parameter [country] can not be empty",
        "A0025" => "Parameter [zipCode] can not be empty",
        "A0026" => "Parameter [email] can not be empty",
        "A0027" => "The parameter [email] format error",
        "A0028" => "Parameter [phone] can not be empty",
        "A0029" => "The parameter [phone] format error",
        "A0030" => "Parameter [shippingFirstName] can not be empty",
        "A0031" => "Parameter [shippingLastName] can not be empty",
        "A0032" => "Parameter [shippingAddress] can not be empty",
        "A0033" => "Parameter [shippingCity] can not be empty",
        "A0034" => "Parameter [shippingCountry] can not be empty",
        "A0035" => "Parameter [shippingZipCode] can not be empty",
        "A0036" => "Parameter [shippingEmail] can not be empty",
        "A0037" => "The parameter [shippingEmail] format error",
        "A0038" => "Parameter [shippingPhone] can not be empty",
        "A0039" => "Parameter [returnURL] can not be empty",
        "A0040" => "Parameter [language] can not be empty",
        "A0041" => "Parameter [billNo] can not be empty",
        "A0042" => "The parameter [billNo] format error",
        "A0043" => "Parameters [billNo] repeat",
        "A0044" => "Merchant does not exist",
        "A0045" => "Merchant is not open",
        "A0046" => "Currency Error",
        "A0047" => "Verify signature failed",
        "A0048" => "Channel not open",
        "A0049" => "Currency exchange rate not set",
        "A0050" => "Parameter [ip] can not be empty",
        "A0051" => "Deal is being processed",
        "R0001" => "Monthly turnover exceeds the limit",
        "R0002" => "The daily turnover exceeds the limit",
        "R0003" => "The black card",
        "R0004" => "The black card Bin",
        "R0005" => "Black email",
        "R0006" => "Black IP",
        "R0007" => "Merchants black card",
        "R0008" => "Merchants black email",
        "R0009" => "Merchants black IP",
        "R0010" => "The number of successful transactions of the same card number and the same merchant exceeds",
        "R0011" => "The number of successful transactions within one day for the same merchant with the same time",
        "R0012" => "The number of successful transactions of the same merchant within one day exceeds the limit",
        "R0013" => "The number of successful transactions within one day for the same merchant with the same IP",
        "R0014" => "The number of failures of the same card number exceeds the limit within a certain period of time",
        "R0015" => "The number of transactions with the same card number exceeds the limit within a certain period of time",
        "R0016" => "The number of failures in the same mailbox exceeded the limit in a certain period of time",
        "R0017" => "The number of transactions in the same mailbox exceeds the limit in a certain period of time",
        "R0018" => "The number of failures of the same phone number in a certain period of time exceeded the limit",
        "R0019" => "The number of transactions on the same phone number exceeds the limit in a certain period of time",
        "R0020" => "The number of failures over a certain period of time for the same IP exceeds the limit",
        "R0021" => " The number of transactions of the same IP exceeds the limit in a certain period of time",
        "R0022" => "Website inactive",
        "R0023" => "The number of successful payment by the same card number and the same store",
        "R0024" => "The number of successful payment by the same email address and the same store",
        "R0025" => "The number of CARDS used by different stores in the same mailbox",
        "R0026" => "The amount paid is greater than the upper limit of the amount limit",
        "R0027" => "The amount paid is less than the limit of the amount",
        "R0028" => "High risk trading",
        "R0029" => "The number of terminal transactions exceeds the limit",
        "R0030" => "High risk Country!",
        "R0031" => "High risk Country!",
        "R0032" => "High risk Country!",
        "R0033" => "High risk Country!",
        "R0034" => "High risk Country!",
        "R0035" => "High risk trading!",
        "R0036" => "Black mobile phone number!",
        "R0037" => "Black mobile phone number!",
        "R0038" => "The number of daily transactions exceeds the limit!",
        "R0039" => "Limit card number!",
        "R0040" => "Limit card email!",
        "R0041" => "Limit white group!",
        "R0042" => "The maximum amount of a single terminal exceeds the limit",
        "R0043" => "merchant black cardBin!",
        "R0045" => "Limit card number!",
        "R0046" => "Card Not on the whitelist!",
        "R0047" => "Eail Not on the whitelist!",
        "R0048" => "Not on the whitelist!",
        "R0061" => "Limited card per designated risk control",
        "R0062" => "Insufficient funds times over limit",
    ];

    public static $fixable_errors_codes = [
        "A0009",
        "A0010",
        "A0039",
        "A0013",
        "A0014",
        "A0011",
        "A0012",
        "A0016",
        "A0017",
        "A0018",
        "A0019",
        "A0020",
        "A0021",
    ];

    /**
     * Check if the response code is fixable and ensure it is not marked as failed
     *
     * @param  string  $code
     * @return bool
     */
    public static function isFixableViaMerchant(string $code): bool
    {
        return collect(self::$fixable_errors_codes)->contains($code);
    }
}
